### ISSUE TITLE
JuliaCon site uses a gem but we have no gem file setup

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaCon/www.juliacon.org#236]
We have a dependency on "jekyll-redirect-from" but no instructions or the like setup to install it.

**Comment by logankilpatrick** [comment]
I keep getting: 
```
logankilpatrick@Logans-MBP www.juliacon.org % gem install jekyll-redirect-from 
Ignoring eventmachine-1.2.7 because its extensions are not built. Try: gem pristine eventmachine --version 1.2.7
Ignoring ffi-1.13.1 because its extensions are not built. Try: gem pristine ffi --version 1.13.1
Ignoring http_parser.rb-0.6.0 because its extensions are not built. Try: gem pristine http_parser.rb --version 0.6.0
Ignoring sassc-2.4.0 because its extensions are not built. Try: gem pristine sassc --version 2.4.0
ERROR:  Error installing jekyll-redirect-from:
	ERROR: Failed to build gem native extension.

    current directory: /Users/logankilpatrick/.gem/ruby/2.6.0/gems/ffi-1.13.1/ext/ffi_c
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby -I /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0 -r ./siteconf20201222-40441-1ep4k7p.rb extconf.rb
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:467:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:546:in `block in try_link0'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/tmpdir.rb:93:in `mktmpdir'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:543:in `try_link0'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:570:in `try_link'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:672:in `try_ldflags'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:1832:in `pkg_config'
	from extconf.rb:9:in `system_libffi_usable?'
	from extconf.rb:42:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Users/logankilpatrick/.gem/ruby/2.6.0/extensions/universal-darwin-20/2.6.0/ffi-1.13.1/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /Users/logankilpatrick/.gem/ruby/2.6.0/gems/ffi-1.13.1 for inspection.
Results logged to /Users/logankilpatrick/.gem/ruby/2.6.0/extensions/universal-darwin-20/2.6.0/ffi-1.13.1/gem_make.out

```

When I follow the instructions here: https://github.com/jekyll/jekyll-redirect-from#installation

**Comment by ViralBShah** [comment]
We really should migrate to Franklin.

**Comment by logankilpatrick** [comment]
Was just thinking this :)

**Comment by aviks** [comment]
The canonical way to run this is in travis, so see here for what is required: https://github.com/JuliaCon/www.juliacon.org/blob/src/.travis.yml

**Comment by ViralBShah** [comment]
BTW, we can do the new site in Franklin, while keeping the old site as static in a separate repo - if we want to avoid moving everything to Jekyll.

**Comment by aviks** [comment]
Site migrated to Franklin.
